### ISSUE TITLE
Мой отчет о результатах комита

### ISSUE THREAD

**Issue by UMSF-K13-3-Hmil** [UMSF-K13-3-Hmil/UMSF-K13-3-Hmil-MainProject#1]
![default](https://cloud.githubusercontent.com/assets/19725001/15771029/923ea18e-2970-11e6-8c36-2f962902932d.JPG)

**Comment by Smoktii** [comment]
Нет модулей

**Comment by UMSF-K13-3-Hmil** [comment]
каких модулей?

**Comment by Smoktii** [comment]
Закрыт по единственному файлу, загруженному в проект
